config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "experiences#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :experiences do
    resources :reviews, only: [:new, :create, :edit, :update, :destroy]
    resources :bookings, only: [:new, :create, :destroy]
  end
  get "bookings", to: "bookings#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :experience
end

app/models/experience.rb
class Experience < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :bookings, dependent: :destroy
  belongs_to :user
  has_many_attached :photos

  validates :category, :title, :location, :description, presence: true

  def average_rating
    reviews.average(:rating).to_f
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :experience

  validates :comment, presence: true, length: { maximum: 250 }
  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews
  has_many :experiences
  has_many :bookings, dependent: :destroy

  validates :first_name, :last_name, presence: true, length: { minimum: 2, maximum: 50 }
  # validates_format_of :password, with: /(?=.[!@#$%&].[!@#$%&])/
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :age, :role])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :age, :role])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_experience, only: %i[new create]

  def index
    # @bookings = Booking.all
    @bookings = current_user.bookings
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.experience = @experience
    @booking.user = current_user

    # find all the bookings with the same experience as the one we're trying to create the booking for
    # loop over the booking that we find
    # check if the starting date overlaps the new one we are trying to create

    if @booking.save
      redirect_to experience_path(@experience), notice: "Booking Created"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to experience_booking_path, status: :see_other
  end

  private

  def set_experience
    @experience = Experience.find(params[:experience_id])
  end

  def booking_params
    params.require(:booking).permit(:date_start, :date_end)
  end
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:query].present?
      sql_query = <<~SQL
        experiences.title @@ :query
        OR experiences.description @@ :query
        OR experiences.category @@ :query
        OR experiences.location @@ :query
        OR users.first_name @@ :query
        OR users.last_name @@ :query
      SQL
      @experiences = Experience.joins(:user).where(sql_query, query: "%#{params[:query]}%")
      if @experiences.empty?
        flash[:notice] = "No results found for '#{params[:query]}'. Please try again."
        redirect_back(fallback_location: experiences_path)
      end
    else
      @experiences = Experience.all
    end
  end


  def show
    @experience = Experience.find(params[:id])
    # fetch the reviews of the experience and set them in a global variable to gain access to them in the show html
    @reviews = @experience.reviews
  end

  def new
    @experience = Experience.new
  end

  def create
    @experience = Experience.new(experiences_params)
    @experience.user = current_user
    if @experience.save
      redirect_to experiences_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @experience = Experience.find(params[:id])
  end

  def update
    @experience = Experience.find(params[:id])
    @experience.update(experiences_params)
    redirect_to experiences_path
  end


  def destroy
    @experience = Experience.find(params[:id])
    @experience.destroy
    redirect_to experiences_path, status: :see_other
  end

  private

  def experiences_params
    # Guillaume added :photo
    params.require(:experience).permit(:title, :category, :location, :description, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_experience, only: [:new, :create, :edit, :update]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.experience = @experience
    @review.user = current_user
    if @review.save
      redirect_to experience_path(@experience)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])
    @review.update(review_params)
    redirect_to experience_path(@review.experience)
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to experience_path(@review.experience), status: :see_other
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end

  def set_experience
    @experience = Experience.find(params[:experience_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container">
  <% @bookings.each do |booking| %>
    <div class="card mb-3">
      <div class="card-header">
        <%= booking.experience.title %>
      </div>
      <div class="card-body">
        <% if booking.date_start %>
          <p><strong>Start Date:</strong> <%= booking.date_start.strftime("%B %d, %Y") %></p>
        <% end %>
        <% if booking.date_end %>
          <p><strong>End Date:</strong> <%= booking.date_end.strftime("%B %d, %Y") %></p>
        <% end %>
        <%= link_to "Delete", experience_booking_path(booking.experience, booking), class: "btn btn-ghost", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
      </div>
    </div>
  <% end %>
</div>

app/views/bookings/new.html.erb
<div class="container-form">
  <h1>Book this experience</h1>
  <%= render "experiences/show_details_in_form", experience: @experience %>
  <div class="form">
    <%= simple_form_for [@experience, @booking] do |f| %>
      <%= f.input :date_start, as: :date, html5: true %>
      <%= f.input :date_end, as: :date, html5: true %>
      <div class="form-actions">
        <%= f.submit "Book", class: "btn btn-ghost"%>
        <%= link_to "Back", experience_path(@experience.id), class: "btn btn-ghost"%>
      </div>
    <% end %>
  </div>
</div>

<script>
  $(function() {
    $('.datepicker').datepicker();
  });
</script>

app/views/experiences/_home_experience.html.erb
<div class="card-experience">
  <% if experience.photos&.attached? %>
    <div class="card-experience-photo" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path experience.photos.first.key, crop: :fill %>')"></div>
  <% end %>
  <div class="card-experience-description">
    <p><i class="fa-solid fa-star"></i> <%= experience.average_rating.round(1) %></p>
    <h4><%=experience.title[0,40]+"..."%></h4>
<p><%= experience.description[0,250]+"..."%></p>
  </div>
  <%= link_to '', experience_path(experience.id), class: 'card-link'%>
</div>

app/views/experiences/_home_links.html.erb
<div class="links-box">
    <%="Popular experiences"%>
    <%= link_to "Add an experience", new_experience_path, class: "btn btn-ghost"%>
</div>

app/views/experiences/_home_marketing.html.erb
<div>
  <div class="cards-marketing">
    <div class="card-marketing">
      <i class="fa-solid fa-coins"></i>
      <h4>Get the best prices</h4>
      <p>Support local guides and book your tours at reasonable prices from a reliable source</p>
    </div>
    <div class="card-marketing">
      <i class="fa-solid fa-user-shield"></i>
      <h4>Safety Comes First</h4>
      <p>All guides completed a background check and are reviewed in-person</p>
    </div>
    <div class="card-marketing">
      <i class="fa-solid fa-medal"></i>
      <h4>Authentic Experience</h4>
      <p>All our guides are locals to the area in which they operate and know the best spots by heart! </p>
    </div>
  </div>
</div>

app/views/experiences/_marketing.html.erb
<div class="background-grey">
  <div class="container cards-experiences">
    <div class="card-marketing">
      <i class="fa-solid fa-coins"></i>
      <h4>Get the best prices</h4>
      <p>Support local guides and book your tours at reasonable prices from a reliable source</p>
    </div>
    <div class="card-marketing">
      <i class="fa-solid fa-user-shield"></i>
      <h4>Safety Comes First</h4>
      <p>All guides completed a background check and are reviewed in-person</p>
    </div>
    <div class="card-marketing">
      <i class="fa-solid fa-medal"></i>
      <h4>Authentic Experience</h4>
      <p>All our guides are locals to the area in which they operate and know the best spots by heart! </p>
    </div>
  </div>
</div>

app/views/experiences/_review.html.erb
  <div class="card card-review text-dark bg-light border-dark" >
    <div class="card-header">
      Rating: <%= review.rating %>/5
      <% if review.user_id == current_user.id %>
        <%= link_to "Edit", edit_experience_review_path(@experience, review), class: 'btn btn-ghost' %>
        <%= link_to "Delete", experience_review_path(@experience, review), class: "btn btn-ghost", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
      <% end %>
    </div>
    <div class="card-body">
      <p class="card-text"> <%= review.comment %> </p>
    </div>
    <div class="card-footer text-muted">
      By <%= review.user.first_name %> <%= review.user.last_name %> | <%= review.created_at %>
    </div>
  </div>

app/views/experiences/_search_form.html.erb
<div class="search-form">
  <div class="form-data form-location">
    <p>search destination</p>
    <i class="fa-solid fa-location-dot"></i>
  </div>
  <div class="form-data form-date">
    <i class="fa-solid fa-calendar-days"></i>
    <p>dates</p>
  </div>
  <i class="form-data form-submit fa-solid fa-magnifying-glass"></i>
  <% link_to "", "#"%>
</div>

app/views/experiences/_show_details_in_form.html.erb
  <h2><%= "#{experience.title} (#{experience.location})"%></h2>
  <% if experience.photos&.attached? %>
    <div class="form-photo-height" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path experience.photos.first.key, crop: :fill %>')"></div>
  <% end %>

app/views/experiences/edit.html.erb
<div class="container-form">
  <h1>Edit this experience</h1>
  <%= render "show_details_in_form", experience: @experience %>
  <div class="form">
  <%= simple_form_for @experience do |f| %>
    <%= f.input :title %>
    <%= f.input :category %>
    <%= f.input :location %>
    <div class="form-actions">
      <%= f.submit "Edit Experience", class: "btn btn-ghost"%>
      <%= link_to "Back", experience_path(@experience.id), class: "btn btn-ghost"%>
    </div>
  <% end %>
  </div>
</div>

app/views/experiences/index.html.erb
<div>

  <div class="image-front"
    style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= image_path 'motocross.jpg' %>')">
    <h1 class="image-front-text">Find thousands of experiences all around the world.</h1>
    <div class="container rounded search-bar">
      <%= form_with url: experiences_path, method: :get, class: "d-flex", id: "search-form" do %>
        <%= text_field_tag :query,
          params[:query],
          id: "form-search-bar",
          class: "form-control",
          placeholder: "Search by location"
        %>
        <%= submit_tag "Search", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
  <div class="container">
    <%= render "home_marketing" %>
    <%= render "home_links" %>
  </div>
  <hr class="cards-experience-line" />
  <div class="container">
    <div class="cards-experiences">
      <% @experiences.each do |experience|  %>
        <%= render "home_experience", experience: experience %>
      <% end %>
    </div>
  </div>
</div>

app/views/experiences/new.html.erb
<div class="container-form">
  <h1>Create an experience</h1>
  <div class="form-photo-height" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= image_path 'motocross.jpg', crop: :fill %>')"></div>

  <div class="form">
  <%= simple_form_for @experience do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :category %>
    <%= f.input :location %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <div class="form-actions">
      <%= f.submit "Create Experience", class: "btn btn-ghost" %>
      <%= link_to "Back", experiences_path, class: "btn btn-ghost"%>
    </div>
  <% end %>
  </div>
</div>

app/views/experiences/show.html.erb
<div class="container">
  <div class="btn-above-photo">
    <div id="back">
      <%= link_to "Back", experiences_path, class:"btn btn-ghost"%>
    </div>

    <div id="edit-experience">
      <% if current_user.id ==  @experience.user_id%>
        <%= link_to "Edit Experience", edit_experience_path(@experience), class: "btn btn-ghost"%>
        <%= link_to "Remove Experience", experience_path(@experience), class: "btn btn-ghost", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
      <% end %>
    </div>
  </div>
  <div class="banner-show">
    <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-inner">


        <% @experience.photos.each_with_index do |photo, index| %>
          <% if index == 0  %>
              <div class="carousel-item active">
              <%= cl_image_tag photo.key, class: "image-experience" %>
              </div>
            <% else  %>
              <div class="carousel-item">
              <%= cl_image_tag photo.key, class: "image-experience" %>
              </div>
            <% end %>
        <% end %>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  </div>
</div>




<div class="experience-info">
  <div class="container exp-container">
    <div class="row row-cols-auto">

      <div class="col-md-12">
        <% if current_user.id !=  @experience.user_id%>
          <h2><%= @experience.title %></h2><%= link_to "Reserve dates", new_experience_booking_path(@experience), class: 'btn btn-success' %>
        <% end %>
      </div>
        <h4><%= @experience.location %> | <%= @experience.category %></h4>
        <p><%= @experience.description %></p>
      <div class="title-of-experience">
        <% if current_user.id !=  @experience.user_id%>
          <%= link_to "Add a review", new_experience_review_path(@experience), class: "btn btn-ghost"%>
        <% end %>
      </div>
    </div>
  </div>
</div>


<div class="review">
  <div class="container">
    <div class="cards-review">
       <% @reviews.reverse.each do |review| %>
        <%= render "review", review: review %>
       <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DrGuide</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_include_tag 'https://code.jquery.com/jquery-3.6.0.min.js' %>
    <%= javascript_include_tag 'https://code.jquery.com/ui/1.12.1/jquery-ui.min.js' %>
    <%= stylesheet_link_tag 'https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/flashes" %>
  </body>
</html>

app/views/reviews/edit.html.erb
<div class="container-form">
  <h1>Edit your review</h1>
  <%= render "experiences/show_details_in_form", experience: @experience %>
  <div class="form">
  <%= simple_form_for [@experience, @review] do |f| %>
    <%= f.input :comment %>
    <%= f.input :rating %>
    <div class="form-actions">
      <%= f.submit "Update review", class: "btn btn-ghost"%>
      <%= link_to "Back", experience_path(@experience), class: "btn btn-ghost"%>
    </div>
  <% end %>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="container-form">
  <h1>Create a Review</h1>
  <%= render "experiences/show_details_in_form", experience: @experience %>
    <%= simple_form_for [@experience, @review] do |f| %>
      <%= f.input :comment %>
      <%= f.input :rating %>
      <div class="form-actions">
        <%= f.submit "Submit review", class: "btn btn-ghost"%>
        <%= link_to "Back", experience_path(@experience), class: "btn btn-ghost" %>
      </div>
    <% end %>
  <%= link_to "Go back", experience_path(@experience), class: "btn btn-ghost" %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <div class="container-fluid">
    <div class="container-flex">
      <%= link_to experiences_path, class: "navbar-brand" do %>
        <%= image_tag "logo-dark.png", width: 45, height: 35, crop: :fill%>
      <% end %>
    </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", experiences_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Bookings", bookings_path, class: "dropdown-item" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
          </li>
          <li class="nav-item dropdown">
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>